### ISSUE TITLE
v0.26.5 on atom atom v0.187.0 fails to activate

### ISSUE THREAD

**Issue by sinkingshriek** [Glavin001/atom-beautify#328]
Currently have `node v0.12.0` installed. And I'm not sure if it was from the upgrade of `atom` or `atom-beautify` (I upgraded them both at the same time) whenever I try to activate with `Ctrl-Alt-b` it throws error message with the following stacktrace. From a quick glance it looks like it has to do with one of `winston's` function being undefined.

*Stacktrace*

```
TypeError: undefined is not a function
  at Writable.<anonymous> (.atom/packages/atom-beautify/node_modules/winston/lib/winston/transports/file.js:60:12)
  at Writable.emit (events.js:138:20)
  at onwriteError (_stream_writable.js:319:10)
  at onwrite (_stream_writable.js:337:5)
  at WritableState.onwrite (_stream_writable.js:107:5)
  at Writable._write (_stream_writable.js:432:3)
  at doWrite (_stream_writable.js:303:12)
  at writeOrBuffer (_stream_writable.js:290:5)
  at Writable.write (_stream_writable.js:219:11)
  at [object Object].File._write (.atom/packages/atom-beautify/node_modules/winston/lib/winston/transports/file.js:195:18)
  at [object Object].File.log (.atom/packages/atom-beautify/node_modules/winston/lib/winston/transports/file.js:167:10)
  at emit (.atom/packages/atom-beautify/node_modules/winston/lib/winston/logger.js:186:17)
  at /usr/share/atom/resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:125:13
  at Array.forEach (native)
  at _each (/usr/share/atom/resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:46:24)
  at Object.async.each (/usr/share/atom/resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:124:9)
  at [object Object].Logger.log (.atom/packages/atom-beautify/node_modules/winston/lib/winston/logger.js:214:9)
  at Uncrustify.target.(anonymous function) [as verbose] (.atom/packages/atom-beautify/node_modules/winston/lib/winston/common.js:52:18)
  at Uncrustify.module.exports.Beautifier.setupLogger (.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:197:10)
  at Uncrustify.Beautifier (.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:204:10)
  at new Uncrustify (.atom/packages/atom-beautify/src/beautifiers/uncrustify/index.coffee:12:5)
  at .atom/packages/atom-beautify/src/beautifiers/index.coffee:79:17
  at Function.map (/usr/share/atom/resources/app/node_modules/cheerio/node_modules/lodash/dist/lodash.js:3508:27)
  at new Beautifiers (.atom/packages/atom-beautify/src/beautifiers/index.coffee:77:26)
  at Object.<anonymous> (.atom/packages/atom-beautify/src/beautify.coffee:9:18)
  at Object.<anonymous> (.atom/packages/atom-beautify/src/beautify.coffee:3:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:672:34)
  at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:236:14)
  at /usr/share/atom/resources/app/src/package.js:742:29
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:227:20)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:182:20)
```

Don't know if it matters but I'm on `Ubuntu 15.04`.
But I've reverted back the version to `v0.26.0` to get it working again.

**Comment by Glavin001** [comment]
Thanks for creating this separate issue.

Could you run `Atom Beautify: Help Debug Editor` command and let me know the results. Thanks.

**Comment by sinkingshriek** [comment]
@Glavin001 It's working in `v 0.27.1` but just for the sake of debugging purposes for future, I downgraded to `v 0.26.5` and here's a straight copy/paste from the clipboard.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 3.19.0-16-generic
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.26.5

### Stack Trace

Failed to activate the atom-beautify package

```
At undefined is not a function

TypeError: undefined is not a function
  at Writable.<anonymous> (/home/me/.atom/packages/atom-beautify/node_modules/winston/lib/winston/transports/file.js:60:12)
  at Writable.emit (events.js:138:20)
  at onwriteError (_stream_writable.js:319:10)
  at onwrite (_stream_writable.js:337:5)
  at WritableState.onwrite (_stream_writable.js:107:5)
  at Writable._write (_stream_writable.js:432:3)
  at doWrite (_stream_writable.js:303:12)
  at writeOrBuffer (_stream_writable.js:290:5)
  at Writable.write (_stream_writable.js:219:11)
  at [object Object].File._write (/home/me/.atom/packages/atom-beautify/node_modules/winston/lib/winston/transports/file.js:195:18)
  at [object Object].File.log (/home/me/.atom/packages/atom-beautify/node_modules/winston/lib/winston/transports/file.js:167:10)
  at emit (/home/me/.atom/packages/atom-beautify/node_modules/winston/lib/winston/logger.js:186:17)
  at /usr/share/atom/resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:125:13
  at Array.forEach (native)
  at _each (/usr/share/atom/resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:46:24)
  at Object.async.each (/usr/share/atom/resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:124:9)
  at [object Object].Logger.log (/home/me/.atom/packages/atom-beautify/node_modules/winston/lib/winston/logger.js:214:9)
  at Uncrustify.target.(anonymous function) [as verbose] (/home/me/.atom/packages/atom-beautify/node_modules/winston/lib/winston/common.js:52:18)
  at Uncrustify.module.exports.Beautifier.setupLogger (/home/me/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:197:10)
  at Uncrustify.Beautifier (/home/me/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:204:10)
  at new Uncrustify (/home/me/.atom/packages/atom-beautify/src/beautifiers/uncrustify/index.coffee:12:5)
  at /home/me/.atom/packages/atom-beautify/src/beautifiers/index.coffee:79:17
  at Function.map (/usr/share/atom/resources/app/node_modules/cheerio/node_modules/lodash/dist/lodash.js:3508:27)
  at new Beautifiers (/home/me/.atom/packages/atom-beautify/src/beautifiers/index.coffee:77:26)
  at Object.<anonymous> (/home/me/.atom/packages/atom-beautify/src/beautify.coffee:9:18)
  at Object.<anonymous> (/home/me/.atom/packages/atom-beautify/src/beautify.coffee:3:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:672:34)
  at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:236:14)
  at /usr/share/atom/resources/app/src/package.js:742:29
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:227:20)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:246:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -0:03.7 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:01.3 core:confirm (atom-text-editor.editor.mini)
     -0:00.5 beautify:help-debug-editor (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "terminal-panel",
      "emmet",
      "restore-windows",
      "save-session",
      "open-in-browser"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "ignoredNames": [
      "*.class",
      "*.*.bak"
    ]
  },
  "atom-beautify": {
    "_analyticsUserId": "99074e74-1669-4692-8f7e-f3bbae79cf5c"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.26.5
atom-grails, v0.1.0
atom-html-preview, v0.1.6
autocomplete-plus, v2.7.1
color-picker, v1.7.0
jshint, v1.3.1
language-groovy, v0.4.0
markdown-preview, v0.148.0
minimap, v4.8.0
monokai, v0.14.0
project-manager, v1.15.5
sync-settings, v0.2.2
vim-mode, v0.46.0
web-browser, v1.4.4

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
Thanks.

Is this still occurring on the latest release?

**Comment by sinkingshriek** [comment]
Hm..sorry for misleading you there. Doesn't seem to be working still.

**Comment by nkete** [comment]
I had the same issue.
`Ubuntu 14.04`
`nodejs 0.10.25`
`atom 0.184.0`
`atom-beautify 0.27.1`

atom update to `0.198.0` fixed this for me

**Comment by avarabei** [comment]
Same issue with  0.179.0

**Comment by Glavin001** [comment]
So from the initial error stack trace, here are links to the applicable code:
- https://github.com/winstonjs/winston/blob/master/lib/winston/transports/file.js#L60
- https://github.com/Glavin001/atom-beautify/blob/master/src/logger.coffee#L40
- https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/beautifier.coffee#L191
- https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/beautifier.coffee#L197

So looks like the writable stream does not have it's `on` method so when Winston tries to call `stream.on` it errors like the stack above. I am not sure why this would happen intermittently, as I do not experience this. I'll keep looking into this. Thanks for your report.

**Comment by Glavin001** [comment]
@nkete:
> atom update to 0.198.0 fixed this for me

I am on Atom 0.199 and am not experiencing this issue.

Please update Atom. Let me know if this does or does not fix this. I am closing this, assuming updating Atom is the solution as indicated by @nkete.

**Comment by sinkingshriek** [comment]
Yup. Seems to be working now.
Atom:- v.199.0
atom-beautify:- 0.27.2
Ubuntu:- 15.04
Thanks. :+1:
