### ISSUE TITLE
Cannot find module 'lib/csspretty.js'

### ISSUE THREAD

**Issue by silver-mx** [Glavin001/atom-beautify#588]
I just installed atom-beautify, selected a javascript fragment in an HTML file to be formatted, and typed Ctrl + Alt + B to use the plugin, but I got the error 'Cannot find module 'lib/csspretty.js'' (see stacktrace below):

Version: 0.28.14 (Linux Mint 17 64x)

OBS 1: I have tried to reinstall several times with no success.
OBS 2: 'lib/csspretty.js' exists in ~/.atom/packages/atom-beautify/node_modules/prettydiff/lib, but for some reason prettydiff does not work fine. Could it be a bug in prettydiff or something I need to configure?

Cannot find module 'lib/csspretty.js'
Hide Stack Trace
Error: Cannot find module 'lib/csspretty.js'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at core_ (/home/diego/.atom/packages/atom-beautify/node_modules/prettydiff/prettydiff.js:732:44)
  at prettydiff_ (/home/diego/.atom/packages/atom-beautify/node_modules/prettydiff/prettydiff.js:1643:16)
  at Object.commonjs [as api] (/home/diego/.atom/packages/atom-beautify/node_modules/prettydiff/prettydiff.js:1678:16)
  at /home/diego/.atom/packages/atom-beautify/src/beautifiers/prettydiff.coffee:106:27
  at tryCatcher (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._resolveFromResolver (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:480:31)
  at new Promise (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:70:37)
  at PrettyDiff.module.exports.PrettyDiff.beautify (/home/diego/.atom/packages/atom-beautify/src/beautifiers/prettydiff.coffee:55:16)
  at /home/diego/.atom/packages/atom-beautify/src/beautifiers/index.coffee:452:24
  at tryCatcher (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._resolveFromResolver (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:480:31)
  at new Promise (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:70:37)
  at /home/diego/.atom/packages/atom-beautify/src/beautifiers/index.coffee:322:18
  at tryCatcher (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._settlePromiseFromHandler (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:507:31)
  at Promise._settlePromiseAt (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:581:18)
  at Promise._settlePromises (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:697:14)
  at Async._drainQueue (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:123:16)
  at Async._drainQueues (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:133:10)
  at MutationObserver.Async.drainQueues (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:15:14)

**Comment by Glavin001** [comment]
Normally I recommend reinstalling and that fixes issues similiar to this.

Since you have tried that already, @prettydiff  any ideas?

**Comment by prettydiff** [comment]
Looking... probably related to the massive code reorganization I just launched yesterday.

**Comment by prettydiff** [comment]
Still waiting for atom-beautify update to complete, but I successfully tested on my local command line by running these following commands:

    npm install prettydiff
    cd node_modules/prettydiff
    node api/node-local.js mode:"beautify" readmethod:"screen" source:"a{color:red;}"

It is also working from the web tool at http://prettydiff.com/

**Comment by prettydiff** [comment]
The big change in the recent update is that the files in the `lib` folders are now true stand-alone modules/libraries.  Before I provided these files as a convenience but they only contained actual JavaScript function and they were also included in the primary application file: `prettydiff.js`.  Now the lib files can be included by Node and Require.js directly without the prettydiff.js file and the prettydiff.js is just a hollow configuration shell.  In the near future I will retire the prettydiff.js file and put all shell instructions into the files located in the `api` directory.

This was also a big change because I was able to create a module scheme that does not require a build process on any platform.  It works natively on the three supported platforms: web, node, and WSH.  The challenge there is that the library files reference each other, so upon require I bind them to a global object named `global`.  The libraries must be executed using a reference different than what they are internally declared with otherwise they create an infinite recursive loop in node.

**Comment by prettydiff** [comment]
@silver-mx could you paste your html/javascript code to a gist so I can attempt to reproduce the issue against that specific code sample?

**Comment by prettydiff** [comment]
I can reproduce the error in Atom by running atom-beautify.  It appears to be an Atom specific problem.  I am continuing to investigate.

**Comment by prettydiff** [comment]
Found the problem.  The problem is with the relative path `lib/libraryName.js`.  When I changed these to absolute paths from root then this worked.  I don't have a solution yet.

**Comment by prettydiff** [comment]
Problem is resolved for me.  Please verify independently.

**Comment by silver-mx** [comment]
I tested in the morning (here in Sweden) and got "TypeError: prettydiff.api is not a function", but now I tested in another computer and I got again:

Cannot find module 'lib/csspretty.js'

Looks like you guys reverted something right?

**Comment by prettydiff** [comment]
I have just tested by following these steps:

1. uninstall atom-beautify
2. install atom-beautify
3. close atom
4. open atom and beautify a file with extension: scss, less, or xml

History of this issue:

* The issue was initially created with the release of v1.14.0.  In this release I discovered Atom can only process relative local file system paths from coffeeScript code.  File paths in JavaScript code are always absolute.
* In v1.14.1 I fixed the above issue and created a new problem by changing the `main` property in the package.json file.
* In v1.14.2 I regressed the change to the package.json file, but otherwise completely left the other changes from v1.14.1 in place as these resolutions remain valid.

**Comment by Glavin001** [comment]
The key is reloading Atom between uninstall and re-install of Atom Beautify and its dependencies such as Pretty Diff.

**Comment by prettydiff** [comment]
I think the problem is this: https://github.com/prettydiff/prettydiff/issues/176#issuecomment-145601200

@silver-mx please try again with Pretty Diff v1.14.3

**Comment by silver-mx** [comment]
Yes, it works with Pretty Diff v1.14.3, nice job @prettydiff and thanks @Glavin001. Just one question, I replaced directly prettydiff in my atom repository of packages. If I reinstall atom-beautify, will I get it working or you need to do some magic to use the last version of prettydiff?

**Comment by prettydiff** [comment]
@silver-mx nope, everything you install Atom-Beautify it pulls in the latest NPM modules.  So, you are good to go!

**Comment by Glavin001** [comment]
Looks like this is good to close. Great work everyone! Thanks.
